### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/webgfx-tests#10]
So tests don't need to be stored locally but accessed through the proxy

**Comment by cvan** [comment]
Is this issue to proxy web sites to [inject this JS](https://github.com/MozillaReality/webgfx-tests/blob/d2235a4/src/main/server/http_server.js#L64-L67) without having to run the local server? Or something different?

**Comment by takahirox** [comment]
Will #93 resolve?
