### ISSUE TITLE
Mic permission prompt blocks automatic testing

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/webgfx-tests#100]
I have an application which first requests mic permission and then starts.

A problem of testing it with `webgfx-tests` is mic permission prompt blocks automatic testing. I needed to manually click the prompt to grant the permission.

One of the solutions would be to allow the mic in browser-level or domain-level via browser settings. But this solution has a problem with Chrome. `webgfx-tests` opens Chrome in private (Incognito) mode and private mode seems to reset the settings.

I found `--deny-permission-prompts` command line option in https://peter.sh/experiments/chromium-command-line-switches/ but it didn't seem to work.

Another solution would be booting it up without private mode by removing `--incognito` command line option. It works for my case so far.

So I'd like to suggest booting Chrome up without private mode. (I don't remember what the root reason why it does with private mode is.)

**Comment by midnight-dev** [comment]
If I had to guess, incognito mode prevents caching to disk across different sessions. Without incognito, you're trusting Chrome to keep a consistent, favorable caching behavior for testing through major & minor updates. Could have been a simple preventative measure. However, the server can just tell browsers to not cache any of the files if that was ever a concern.

**Comment by fernandojsg** [comment]
I don't remember exactly how it works without the incognito mode, I guess it will just run your default profile right? If so, we should at least create a new profile, I believe that was the initial approach, as otherwise your profile could affect the benchmark, for example if you have extensions installed or so

**Comment by takahirox** [comment]
> I guess it will just run your default profile right?

I guess so.

> we should at least create a new profile, I believe that was the initial approach, as otherwise your profile could affect the benchmark, for example if you have extensions installed or so

webgfx-tests doesn't use private mode for other browsers. The other browsers have the same problem?
