### ISSUE TITLE
Create an API to build a test runner on top of it

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/webgfx-tests#3]

**Comment by cvan** [comment]
`/store_test_results` is not defined but referenced in [`ResultsServer#storeTestResults`](https://github.com/MozillaReality/webgfx-tests/blob/686eac5/src/frontapp/results-server.js#L30).

I noticed the endpoint is not listed in [`http_server.js`](https://github.com/MozillaReality/webgfx-tests/blob/d2235a48/src/main/server/http_server.js#L40) like so:

```js
    .post('/store_test_results', (req, res) => {
      console.log('Storing test results', req.body);
      res.send('');
    })
```

Should I file a separate issue for that or does this issue cover it?
