### ISSUE TITLE
Sometimes the tests finish but the server freezes

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/webgfx-tests#56]
It happens from time to time that the server just freezes and it doesn't respond. I suspect it's because of the websocket server.

**Comment by fernandojsg** [comment]
I'm getting this problem when running 
```webgfx-tests run aftertheflood-vlq --adb --browser fxr --verbose```
I see the `Test finished` green screen, and the console shows the `test finished` log with the results JSON, but the window is not closed
@takahirox could you give it a try and confirm if you are getting similar result?

**Comment by takahirox** [comment]
`Test passed!` green screen but no `test finished` on the console. Window isn't closed.

Update: Oculus Browser works fine.

**Comment by fernandojsg** [comment]
@takahirox When you say `console` do you mean command line? or browser's console (from remote debugging) ?  Because I don't see it `test finished` on the command line, but I do see it on the browser's console

**Comment by takahirox** [comment]
I meant command line. I'll check browser console.

**Comment by takahirox** [comment]
`Finished!` on JavaScript console. No `test finished` on the command line. No result JSON. Window isn't closed.
