### ISSUE TITLE
Add default (to override) parameters on webgfx-tests.config.json

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/webgfx-tests#74]

**Comment by takahirox** [comment]
~~Related #45~~

**Comment by fernandojsg** [comment]
I didn't express myself correctly. #45 was to let the user use `--overrideparams` from the command line to change parameters added to the `test.json`. 
What I mean here is to add a config file specifically for that, like having `skipRefImagetest: false` for all the tests on tests.json, so we could have multiple profiles

**Comment by takahirox** [comment]
I see so that `default`
