### ISSUE TITLE
Web UI for the command line features

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/webgfx-tests#88]
Currently the web UI is used to launch the tests within the same browser. But if you want to launch tests in a device (using ADB) or in another browser, you need to execute `webgfx-tests run test1 test2 test3...`.
So it could be nice to be able to add the option on the browser UI to run these tests on another browsers or devices without needing to use the command line.

**Comment by midnight-dev** [comment]
These suggestions could use better descriptions. Do you have a PR that demonstrates what you have in mind?

**Comment by fernandojsg** [comment]
@midnight-dev sorry, I was just adding it as a reminder, I added a description already, I hope it's clear enough :) and I don't have a PR yet for that
