### ISSUE TITLE
Hint for finding the target canvas

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/webgfx-tests#98]
`webgfx-tests` assumes the last webgl context being initialized is the one used to rendering. But it is not always true. For example Hubs. If it isn't, `webgfx-tests` requests to manually edit the code.

https://github.com/MozillaReality/webgfx-tests/blob/master/src/client/index.js#L101-L105

```
// We assume the last webgl context being initialized is the one used to rendering
// If that's different, the test should have a custom code to return that canvas
if (CanvasHook.getNumContexts() > 0) {
  var context = CanvasHook.getContext(CanvasHook.getNumContexts() - 1);
  this.canvas = context.canvas;
```

But if I edit for a certain test, other tests can be broken.

So I'd like to suggest `webgfx-tests` takes hint (e.g. canvas dom element id) to find the target canvas. Maybe `tests.json` is a good place to specify?

**Comment by midnight-dev** [comment]
That would be better than optimistically using the previous context. Many 3D viewers (CesiumJS for example) expect a DOM node with a specific ID to which they can attach a context. There's usually an options object passed into constructors that can customize the ID.

The JSON seems like a good place for test configurations. Just for giggles, say the config is missing or that the DOM element isn't found. Should testing fail outright or try to fallback to the previous context? For convenience, I'd say the latter. However, depending on how strict you'd like to be, throwing an error may be preferable. It would force the user to fix the problem before being able to proceed.
